# Generated by Django 5.1.5 on 2025-03-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_customer_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='opportunity',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('Stage_1', 'Stage 1'), ('Stage_2', 'Stage 2'), ('Stage_3', 'Stage 3'), ('not_interested', 'Not Interested')], default='new', max_length=20),
        ),
    ]
