# Generated by Django 5.1.5 on 2025-03-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_rename_opportunity_customer_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('advertisement_confirm', 'Advertisement Confirm'), ('not_interested', 'Not Interested')], max_length=50)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.customer')),
            ],
        ),
    ]
